name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: sudo apt update && sudo apt install build-essential libcurl4-openssl-dev libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev
    - name: make
      run: make
